config/routes.rb
ForumDemo::Application.routes.draw do

  devise_for :users

  resources :boards do
      resources :posts #注意resources与resource的区别。resources对应
  end
  
    namespace :admin do
       resources :boards do
         resources :posts
       end
     end
  
  

   root :to => "boards#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/board.rb
class Board < ActiveRecord::Base
  paginates_per 10
  has_many :posts
  validates_presence_of :name, :on => :create, :message => "can't be blank"
end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 5
  belongs_to :board, :class_name => "Board", :foreign_key => "board_id",:counter_cache => true
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  #default_scope :order => 'created_at DESC'
  scope :recent, :order => 'updated_at DESC'
  has_attached_file :excerpt_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  validates_presence_of :title, :on => :create, :message => "can't be blank"
  validates_presence_of :content, :on => :create, :message => "can't be blank"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  attr_protected :is_admin
  
  has_many :posts
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  
  layout 'admin'
  before_filter :require_is_admin
  before_filter :authenticate_user!,:except=>[:index,:show]

  def index
    redirect_to(boards_path)
  end

  def edit
    @board=Board.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @board=Board.new
    respond_to do |format|
      format.html {  }
    end
    
  end
  
  def create
    @board=Board.new(params[:board])
    respond_to do |format|
      if @board.save
        format.html{redirect_to (board_path(@board),:notice => 'Board was successfully created.')}
      else
        format.html{redirect_to(boards_path)}
      end
    end
   
  end

  def update
    @board=Board.find(params[:id])
    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to(boards_path,:notice => 'Board was successfully updated.')}
      else 
        format.html { render :action => "edit"}
      end
    end
  
  end

  def destroy
    @board=Board.find(params[:id])
    @posts=@board.posts
    @posts.each do |post|
      post.destroy
    end
    @board.destroy 
    respond_to do |format|
      format.html { redirect_to(boards_path) }
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  layout 'admin'
  before_filter :require_is_admin
  before_filter :find_board
  before_filter :authenticate_user!,:except=>[:index]
  #before_filter :current_user_posts
  
  def edit
    #@board=Board.find(params[:board_id])
    #@post=current_user.posts.find(params[:id]),此种写法适合用户，而非管理员
    @post=Post.find(params[:id])
    respond_to do |format|
      format.html {  }
    end
  end
  
  def update
    #@board=Board.find(params[:board_id])
    #@post=current_user.posts.find(params[:id])
    @post=Post.find(params[:id])
    respond_to do |format|
    if @post.update_attributes(params[:post])
        format.html { redirect_to(board_path(@board),:notice => "成功更新")}    
      else 
        format.html { }
      end
    end 
  end 
  
  def destroy

    #@board=Board.find(params[:board_id])
    #@post=current_user.posts.find(params[:id])
    @post=Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to(board_path(@board))}
    end  
  end

  protected
     def find_board
       @board=Board.find(params[:board_id])  
     end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def require_is_admin
    unless(current_user && current_user.is_admin?)
      flash[:alert] = "You must be admin!"
      redirect_to(root_path)
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  before_filter :authenticate_user!,:except=>[:index,:show]
  def index
    #@boards=Board.all
    @boards = Board.order(:id).page(params[:page])
    respond_to do |format|
      format.html
    end
  end

  def show
    @board=Board.find(params[:id])
    @posts =@board.posts.recent.order(:id).page(params[:page])
    respond_to do |format|
      format.html
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :find_board
  before_filter :authenticate_user!,:except=>[:show,:index]
  #before_filter :current_user_posts
  
  def index
    #@board=Board.find(params[:board_id])
    redirect_to board_path(@board)
  end

  def show
    #@board=Board.find(params[:board_id])
    @post=@board.posts.find(params[:id])
  end

  def new
    #@board=Board.find(params[:board_id])
    @post=@board.posts.build #new与build的区别是什么？
  end
  
  def edit
    #@board=Board.find(params[:board_id])
    @post=current_user.posts.find(params[:id])
  end

  def create
    #@board=Board.find(params[:board_id])
    @post =Post.new(params[:post])
    @post.user_id=current_user.id
    @post.board_id=@board.id
    #@post= @board.posts.build(params[:post])
    @post.save
    respond_to do |format|
      format.html { redirect_to(board_path(@board)) }
    end

  end
  
  def update
    #@board=Board.find(params[:board_id])
    @post=current_user.posts.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(board_post_path(@board,@post),:notice => "成功更新")}    
      else 
        format.html { render :action => "edit"}
      end
    end 
  end 
  
  def destroy

    #@board=Board.find(params[:board_id])
    @post=current_user.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to(board_path(@board))}
    end  
  end

  protected
    def find_board
      @board=Board.find(params[:board_id])  
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/boards/_form.html.erb
<div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit %>

app/views/admin/boards/edit.html.erb
<% form_for @board,:url => admin_board_path(@board) do |f| -%>
<%=render :partial => "form",:locals=>{:f=>f}%>
<% end -%>
<%= link_to "back", admin_boards_path %>

app/views/admin/boards/new.html.erb
<% form_for @board,:url => admin_boards_path(@board) do |f| -%>
<%=render :partial => "form",:locals=>{:f=>f}%>
<% end -%>
<%= link_to "back", admin_boards_path %>

app/views/admin/posts/_form.html.erb
<div>
<%= f.label :title, "Title" %>
<%= f.text_field :title %>
</div>
<div>
<%= f.label :content, "Content" %>
<%= f.text_area :content %>
<%= f.submit %>
</div>

app/views/admin/posts/edit.html.erb
<% form_for @post, :url=>admin_board_post_path(@board,@post) do |f| %>
<%=render :partial => "form",:locals=>{:f=>f}%>
<% end -%>
<%= link_to "show", board_post_path(@board, @post) %>
<%= link_to "back", board_posts_path(@board) %>

app/views/boards/_form.html.erb
<div>
<% form_for @board do |f| -%>

  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>
      <ul>
        <% @board.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit %>
<% end -%>
</div>

app/views/boards/edit.html.erb
<%= render 'form'%>
<%= link_to "back", :action => "index" %>

app/views/boards/index.html.erb
<table border="0" cellspacing="5" cellpadding="5">
  <tr><th>name</th></tr>
  <% @boards.each do |board| %>
    <tr>
      <td><%=board.name%></td>
      <td><%= link_to "show", :action => "show", :id => board.id %></td>
    <% if current_user && current_user.is_admin? %>
      <td>
	<%= link_to "A-edit", edit_admin_board_path(board) %>
	</td>
	  <td><%= link_to 'A-Destroy', admin_board_path(board), :confirm => 'Are you sure?', :method => :delete %>
		</td>
	<% end -%>
    </tr>
  <% end -%>
</table>
<%= paginate @boards %>
<% if current_user && current_user.is_admin? %>
<%= link_to "A-new board", new_admin_board_path %>
	<% end -%>
	<ul>
	<li><%= link_to "link text...", boards_path %> #错误写法，board_path => /boards </li>
	<li><%= link_to "link text...", board_path(1) %> # => /board/1</li>
	<li><%= link_to "link text...", edit_admin_board_path(2) %> # => /admin/boards/2/edit</li>
	<li><%= link_to "link text...", new_admin_board_path %> # => admin/boards/new</li>

app/views/boards/new.html.erb
<%=render :partial => "form"  %>
<%= link_to "back", :action => "index" %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>
<div>
	<div>board.id :<%=@board.id%></div>
	<div>board.name:<%=@board.name%></div>
	<div>拥有的帖子数量：<%=@board.posts.size%></div>
</div>
<%= link_to "back", :action => "index" %>


<table border="0" cellspacing="5" cellpadding="5">
	<tr>
		<th>id</th>
		<th>title</th>
		<th>content</th>
		<th>created time</th>
		<th>updated time</th>
	</tr>
	<% @posts.each do |post| %>
	<tr>
		<td><%=post.id%></td>
		<td><%=post.title%></td>
		<td><%=post.content%></td>
		<td><%=post.created_at%></td>
		<td><%=post.updated_at%></td>
		<td><%= link_to "show", board_post_path(@board,post) %></td>
		<% if post.user == current_user %>
		<td><%= link_to "edit", edit_board_post_path(@board,post) %></td>
		<td><%= link_to "destroy", board_post_path(@board,post), :confirm=>"Are you sure",:method=>'delete' %></td>
		<% end -%>
		
		<% if current_user && current_user.is_admin? %>
		<td><%= link_to "A-edit", edit_admin_board_post_path(@board,post) %></td>
		<td><%= link_to "A-destroy", admin_board_post_path(@board,post), :confirm=>"Are you sure",:method=>'delete' %></td>
		<% end -%>
		
	</tr>
	<% end -%>
</table>
<%= paginate @posts %>
<%= link_to "new post", new_board_post_path(@board) %>
<% if current_user && current_user.is_admin? %>
<%= link_to "A-edit", edit_admin_board_path(@board) %>
<% end -%>
<%= link_to "back", boards_path %>

app/views/common/_user_nav.html.erb
<div class="user_navigation">
<% if user_signed_in? %>
Hi! <%= current_user.email %>
<%= link_to("Sign out", destroy_user_session_path)%>
<% if current_user.is_admin? %>
<%= %> <%= link_to "Admin Panel", admin_boards_path %>
<% end -%>
<% else %>
<%= link_to "Sign in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>
<% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<h1> Admin Panel </h1>
<%=render :partial => "common/user_nav"%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%=render :partial => "common/user_nav"%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
hello world!

app/views/posts/_form.html.erb
<div>
<%= f.label :title, "Title" %>
<%= f.text_field :title %>
</div>
<div>
<%= f.label :content, "Content" %>
<%= f.text_area :content %>
<%= f.file_field :excerpt_image %>
<%= f.submit %>
</div>

app/views/posts/edit.html.erb
<% form_for @post, :url=>board_post_path(@board,@post),:html => {:multipart => true }  do |f| %>
<%=render :partial => "form",:locals=>{:f=>f}%>
<% end -%>
<%= link_to "show", board_post_path(@board, @post) %>
<%= link_to "back", board_posts_path(@board) %>

app/views/posts/index.html.erb
<table border="0" cellspacing="5" cellpadding="5">
	<tr><th>title</th>
		<th>content</th>
	</tr>
	<% @posts.each do |post| %>
	<tr>
		<td><%=post.title%></td>
		<td><%=post.content%></td>
		<td><%= link_to "show", :action => "show", :id => post.id %></td>
		<td><%= link_to "edit", :action => "edit", :id => post.id %></td>	
		<td><%= link_to "destroy", post, :confirm=>"Are you sure",:method=>'delete' %></td>
	</tr>
	<% end -%>
</table>
<%= link_to "new", :action => "new" %>

app/views/posts/new.html.erb
<% form_for @post, :url => board_posts_path(@board), :html => {:multipart => true } do |f| -%>

<%=render :partial => "form", :locals => {:f =>f } %>
  
<% end -%>

<%= link_to "back", board_path(@board) %>

app/views/posts/show.html.erb
<p><%=notice%></p>
<div><%=@post.title%></div>
<div><%=@post.content%></div>
<div><%=image_tag @post.excerpt_image.url%></div>
<div><%=image_tag @post.excerpt_image.url(:medium)%></div>
<div><%=image_tag @post.excerpt_image.url(:thumb)%></div>
<% if @post.user=current_user %>
<%= link_to "edit", edit_board_post_path(@board, @post) %>
<% end -%>
<% if current_user && current_user.is_admin? %>
<%= link_to "A-edit", edit_admin_board_post_path(@board, @post) %>
<% end -%>
<%= link_to "back", :action => "index" %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>